### ISSUE TITLE
A public user can download their customized, cloned skill list to a PDF

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#1]

**Comment by Pcushing** [comment]
So this could be the exact same thing as #13 given the way the back-end is set up. However, we might eventually change what the PDF looks like for a published version versus unpublished version of standards. That's TBD from design.

**Comment by littleforest** [comment]
@Pcushing for the short-term, should I go ahead and make a Rails controller/view page for a user's occupation standards, and then they could click a download button? Or just prep the backend piece for when we get an API endpoint in place?

**Comment by Pcushing** [comment]
I think just prep the back-end piece for when an api is in place for now. If you need a quick view to confirm everything's working, go for it, but i wouldnt spend the time to build it out more than that.

**Comment by littleforest** [comment]
@Pcushing will someone other than the creator be able to view/download an occupation standard, or should it return unauthorized?

**Comment by Pcushing** [comment]
I think anyone should be able to download.

**Comment by littleforest** [comment]
Including a guest (not-signed in) user? Or only signed-in users?

**Comment by Pcushing** [comment]
Yeah - not signed in. I think this is a part of the resource that should be available for someone to download regardless of having an account.
