### ISSUE TITLE
Sign up page with so we can invite users to join

### ISSUE THREAD

**Issue by jhash** [WorkHands/RAPiDSkills#114]
We don't need to surface this anywhere yet on the home page. I want to be able to send invites to a controlled subset so we need a page like this to be live (though undiscoverable aside from URL guessing otherwise) so they can sign up.

![RapidSkillsSignUp](https://user-images.githubusercontent.com/47611/74760098-c37ddb80-522e-11ea-88c3-6273322231f3.png)

cc @littleforest as I'm going to prioritize this such that we can start inviting (mostly internal) people this week. I'll work on getting the emails working.

**Comment by Pcushing** [comment]
@jhash nvm. Looks like this is already live. Didn't realize that. reclosing.
