### ISSUE TITLE
The system supports an empty user call that returns the authenticated user (me)

### ISSUE THREAD

**Issue by jhash** [WorkHands/RAPiDSkills#143]

**Comment by littleforest** [comment]
@jhash this already exists if you follow the relationship links that are returned in the session response:

https://www.rapidskills.org/api/v1/docs/#sign-in

<img width="992" alt="Screen Shot 2020-01-22 at 7 57 39 AM" src="https://user-images.githubusercontent.com/1938665/72910148-f8a91380-3cec-11ea-941e-1194af1a7b65.png">
