### ISSUE TITLE
Front-end cleanup notes for Thursday demo session

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#178]
- [x] Copying/duplicating isn’t working.  I get taken to the page of the parent with the new title. If I refresh, that title disappears. It doesn't seem like anything's been created. Hard to test a lot of things bc o f this.

- [x] Pagination so we can get more results!   It looks like we only have 25 results, but there’s like 200+ in the system. Whatever’s easiest to deliver to start -  scrolling or numbered pages you click on

- [x] We need a way to copy (and favorite) from the full view. Definitely a design oversight.  In the short-term, I might just use the Share/Download buttons for this.

- [x] Can we open the first work process by default when you visit a standard? So you can see the skills right away?

- [x] Added logos that’s all 500x500 and we need to reign those in: https://www.rapidskills.org/standards/258

- [ ] Can we display the ONET and Rapid instead of showing text? (Nope, looks like they’re all blank)

- [ ] If work processes is 0,  don’t show it in the card. If skills is 0, same. If total hours is 0, same.

**Comment by jhash** [comment]
Pagination covered by this ticket: https://github.com/WorkHands/RAPiDSkills/issues/180

**Comment by jhash** [comment]
ONET and Rapid codes I'll leave up to you on what to fill with, it looks bad with blanks spaces there IMO, I think that's why I added the default. If they are required for all standards then I say we just validate better and backfill, etc.

**Comment by jhash** [comment]
Duplicating from standard page: https://github.com/WorkHands/RAPiDSkills/issues/181

**Comment by jhash** [comment]
Same thing for not showing the work processes, skills, total hours in the standard cards, it looked real bad to me so we may need an alternative.

**Comment by jhash** [comment]
@Pcushing what part of images need to be reigned in? I have it set to just fill the height of the section it's stuck in on the standard cards (96px / 6rem)

**Comment by jhash** [comment]
@Pcushing opening the first work process seems related to some of the walkthrough designs. I wonder if there is an alternative along that route.

**Comment by jhash** [comment]
Opening the first work process in: https://github.com/WorkHands/RAPiDSkills/pull/218

**Comment by jhash** [comment]
Hey @Pcushing are the ONET and Rapid IDs optional? Should I be accounting for them not being there?

**Comment by Pcushing** [comment]
> Hey @Pcushing are the ONET and Rapid IDs optional? Should I be accounting for them not being there?

Yes. We don't always get either one of these pieces of info. California programs dont use rapids, for example, and a lot of frameworks wont have either.
