### ISSUE TITLE
Back-end cleanup notes for Thursday

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#179]
The first three in here would really help for tomorrow. The rest are likely more long-term and can be moved into individual tickets if that's preferable.

- [x] Get rid of duplicate standards. See Urban Institute: https://www.rapidskills.org/admin/occupation_standards?q%5Borganization_id_eq%5D=44&commit=Filter&order=id_desc

- [x] Remove duplicate organizations (mostly HCAP ones). I do not mean ones where they’re spelled slightly differently. I mean ones where they’re spelled exactly the same. We need to transfer any standards to the dupe we’re keeping, too. This is blocking adding logos for these right now. Ex. https://www.rapidskills.org/admin/organizations?q%5Btitle_contains%5D=1199&commit=Filter&order=id_desc

- [x] We need a way to merge occupations. Both for 1 time clean up and likely on an ongoing basis. https://www.rapidskills.org/admin/occupations?q%5Btitle_contains%5D=truck&commit=Filter&order=id_desc

- [x]  Index view:  drop creator, data trust. Approval, completed at, created at, updated at. Add work processes count, skills count, occupation type (hybrid, competency, etc.), onet, and rapids codes to index and show views.

- [x] When choosing an org / user in dropdown, can we alpha sort these? Ex., New Occupation Standard choose Oragnization or User. https://www.rapidskills.org/admin/occupation_standards/new

- [x] Let’s not include Unregistered standards in our index responses unless someone is requesting their  own standards. That data’s going to be messy for a while. We likely want to leverage the published_at attribute for this, too, so someone could eventually publish an unregistered.

- [x] Link to sidekiq from admin tools isn’t working

- [x] It looks like Rapids/Onet aren’t coming through for any of our imports. Every occupation is blank.  https://www.rapidskills.org/admin/occupations?order=id_desc&page=6

- [x] We need a way  pull down the prod DB instead of running off seed data.

**Comment by littleforest** [comment]
@Pcushing for 

> Index view: drop creator, data trust. Approval, completed at, created at, updated at. Add work processes count, skills count, occupation type (hybrid, competency, etc.), onet, and rapids codes to index and show views.

For the skills count -- do you want the total skills count, including nested within work processes, or just skills count directly linked to the standard?

**Comment by Pcushing** [comment]
@littleforest total skills count.

**Comment by littleforest** [comment]
@Pcushing 

> Let’s not include Unregistered standards in our index responses unless someone is requesting their own standards. 

You mean for the API response, right? Not admin page?

**Comment by Pcushing** [comment]
@littleforest you got it.

**Comment by littleforest** [comment]
@Pcushing should the Occupation table have a unique title?

**Comment by littleforest** [comment]
@Pcushing for using prod data in development -- do you want a periodic export of the prod db available, or is it sufficient to upload the HCAP, Urban Institute, etc. data files as part of a setup phase?

**Comment by Pcushing** [comment]
> should the Occupation table have a unique title?

I think so. 

> for using prod data in development -- do you want a periodic export of the prod db available, or is it sufficient to upload the HCAP, Urban Institute, etc. data files as part of a setup phase?

Just a script or rake task or something we can run to pull down the prod db for local development. The current seeds file is sufficient for the moment, but there's sometimes data issues in prod that arent easily recreated no matter how good our seeding is.

cc @littleforest

**Comment by littleforest** [comment]
@Pcushing seems like a unique key of [:title, :rapids_code, :onet_code] would be a safe bet at minimum, right? I'd like to put a constraint on the database just in case my duplicate bug is not fixed as I think it is.

**Comment by Pcushing** [comment]
@littleforest that's a good start. We may need to evolve as we go but let's start more restrictive.

**Comment by littleforest** [comment]
@Pcushing I re-uploaded the rapid-skills-apprenti.csv and the urban-institute-a.csv to set the rapids/onet codes, but the other files have expired in S3 (I set them to expire after a short while since they're just living in my personal account for now). Do you have copies of those other files you can send me? (or you can try to re-upload yourself too).

**Comment by Pcushing** [comment]
@littleforest 

1. Let's get that off your S3. Is there an easy way for you to share the current bucket set up so I can replicate it on my end?

2. I can't upload csv here so i'll send you what i've got on slack

**Comment by littleforest** [comment]
@pcushing, here's what I would do for transferring S3:

1. (Optional) Create a rapid-skills specific user in IAM with S3 Full access. Give programmatic but not console access.  Skip this if you already have some other WorkHands user account you already use for this kind of thing.

2. Create a bucket in S3 to hold the files. Leave the defaults so it stays private. My bucket is in us-west-1 N. CA, but you can use whatever works for you.

3. If you don't already have the secret keys to open the credentials file, then get them from Heroku:

```
$ heroku config -a rapid-skills-staging | grep RAILS_MASTER_KEY
$ heroku config -a rapid-skills | grep RAILS_MASTER_KEY
```
Store these keys locally in `config/credentials/staging.key` and `config/credentials/production.key`, respectively.

4. Locally, [open the secrets file](https://github.com/WorkHands/RAPiDSkills#secret-keys):

```
$ docker-compose run --rm -e EDITOR=vim web rails credentials:edit --environment staging
$ docker-compose run --rm -e EDITOR=vim web rails credentials:edit --environment production
```

You can substitute another editor if you don't use vim. See the note in the docs about using the `wait` flag for something like Sublime. Haven't actually tested it to see if it works.

5. Replace my credentials and the bucket/region info as appropriate.

**Comment by littleforest** [comment]
@Pcushing see item 10 in the [dev setup notes](https://github.com/WorkHands/RAPiDSkills#development-setup) for script to import prod data.
