### ISSUE TITLE
The index request for standards seems to time out or is at least very slow

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#220]
This became an issue during a call I just had for a demo when the app seemingly timeout / failed. I had to do a quick server restart. I was logged in at the time but I'm not sure if it's limited to that.

I suspect we need to do at least these two things:

- [ ] Majorly limit the relationships included in index requests. Include counts on the standard object (`skill_count`, `work_process_count`, etc.) where needed instead of the full lists.
- [ ] Add some caching

cc @jhash as this'll likely effect where he accesses some of this info on the front-end.

**Comment by littleforest** [comment]
@Pcushing part of this issue is that we're running on a Hobby dyno, and hitting memory quotas. Should we upgrade and see if that solves the issue first?

**Comment by Pcushing** [comment]
@littleforest ah! Yes. I was wondering about that, too.  I'll upgrade now.

**Comment by littleforest** [comment]
Better, but still taking 4 seconds.  Will work on implementing your suggestions.
