### ISSUE TITLE
None of the inputs seem to accept text on Safari

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#235]
I sent an invite to Megan to try out our sign up and she relayed that she couldnt type in any of th einput fields. 

It looks like it's specific to Safari and not specific to the sign up form as I cant type in anything on rapidskills with safari. Firefox and Chrome are fine. I dont have access to IE.

**Comment by jhash** [comment]
@Pcushing old IEs are just straight up not going to work.

Safari is fixable probably. I saw this issue on my phone, it wasn't showing what I was typing.

**Comment by Pcushing** [comment]
@jhash as long as we have some sort of message for the old IEs, that's fine. IT's safari that was more of a red flag for now.
