### ISSUE TITLE
Duplication on work processes in at least one standard

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#261]
https://www.rapidskills.org/standards/350

I'm not sure how widespread it is.

**Comment by littleforest** [comment]
I have found some bugs in my occupation and occupation standard import scripts, and have a fix for those in development.

What is still outstanding is how to handle rows in the import files that match on a rapid code, but the data row implies a different occupation type than the rapids code.  For onet codes that do not match on an existing occupation type, I am currently creating a new occupation.

**Comment by littleforest** [comment]
@Pcushing if you look at lines 2405-2410 in the the hcap-2 file, the rapids code is 1085CB, but the rows look to be a time-based occupation instead.

**Comment by Pcushing** [comment]
@littleforest I would go with what the data says if it differs from the code:
> data row implies a different occupation type than the rapids code
We're compiling these manually so having one field off (the code) is more likely than having an entire occupation's data o ff.
