### ISSUE TITLE
The system can pull occupations, industry code, rapids data from DOL list of apprenticeable occupations for updated occupations

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#34]
https://www.doleta.gov/OA/occupations.cfm

We essentially want to pull everything from this page and periodically update it. I'll build this ticket out in more detail as it'll be one of the first tasks.

**Comment by Pcushing** [comment]
I realized we can make some progress on this even with that page down. The site links to an excel file with the occupations. I have two copies on my machine:

From April 10, 2019:

[Available_Occupations.xlsx](https://github.com/WorkHands/RAPiDSkills/files/3623334/Available_Occupations.xlsx)

From Sep 11, 2019:

[Available_Occupations (1).xlsx](https://github.com/WorkHands/RAPiDSkills/files/3623337/Available_Occupations.1.xlsx)

We can run the initial seed off the most recent and then set up the ability to poll for updates later. I don't know if there's any changes within the documents, but it might be worth a quick script to check. I think we'd really only need to poll 1x every month or so. The initial list here will likely be plenty. The only thing we dont get from the excel file that we'd get from the website is the url to the onet page for that occupation.

**Comment by Pcushing** [comment]
It looks like this page is loading now. FYI.

**Comment by littleforest** [comment]
@Pcushing do we not need a `title` field for the occupations table, or are any Title, Alt Title all going to just end up in the aliases field?

**Comment by Pcushing** [comment]
Yes it should. That's a heck of an oversight on my part. Thanks for
catching!

**Comment by littleforest** [comment]
@Pcushing will occupations be unique by rapids_code?  Or what field(s) should I be using to ensure no duplicates.

Also, I was looking through the Workhands repo to see about the STI for the hybrid, time-based types, but not seeing them.  What names are you using for the submodels, so we have consistency?

**Comment by Pcushing** [comment]
Yes - they should be unique by rapids_code.

Here you go. They're in the engine:

https://github.com/WorkHands/WorkHands/blob/master/engines/apprenticeship/app/models/apprenticeship/occupation.rb
https://github.com/WorkHands/WorkHands/blob/master/engines/apprenticeship/app/models/apprenticeship/hybrid_occupation.rb
https://github.com/WorkHands/WorkHands/blob/master/engines/apprenticeship/app/models/apprenticeship/competency_occupation.rb
https://github.com/WorkHands/WorkHands/blob/master/engines/apprenticeship/app/models/apprenticeship/hour_occupation.rb

The "hour_occupation" should be "time_occupation" so I dont think i'd copy
that from the core project, but the others should work.

**Comment by littleforest** [comment]
For a title like this:

```
FIRER, MARINE (Alternate Title: Fireman, Oiler & Watertender ) (Water Transportation)
```

How should that get parsed into title, and alias(es)? Not sure what to do with the (Water Transportation) on the end.

**Comment by Pcushing** [comment]
Good question. I don't know the exact answer to that. I'll have to look at
a few. Can you just flag these for now and skip that part? Set up a
separate ticket and assign to me to look into.

**Comment by littleforest** [comment]
@Pcushing should I be creating the OccupationsStandards table as part of this ticket, or separately for #8, #9, #10?

**Comment by Pcushing** [comment]
Separately.
