### ISSUE TITLE
The system can support a landing page to collect email addresses of interested users pre-launch

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#35]

**Comment by littleforest** [comment]
@Pcushing I forgot what we talked about for this -- should I create something like a Leads table and store email addresses in the database, or do you have Mailchimp or some other mailing list thing setup that you want me to directly add email addresses to?

**Comment by littleforest** [comment]
Or did we not care about the actual collection yet, and I should just be creating a page which pretends to collect email addresses?

**Comment by Pcushing** [comment]
Good question. Let's use this as an excuse to set up the public users table. Name / email is fine for now.

**Comment by Pcushing** [comment]
Also, since this is our first forray into the front-end, know that we're largely going to re-use the styles from one of the client's existing sites

https://miapprenticeship.org/
