### ISSUE TITLE
Shade out everything but the tip and the focused div so people can see the tips better. They're missing them and the point from the tip

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#373]
Can we gray out everything but the div in focus and the tooltip? They couldnt see that these were pointing at anything.

![image](https://user-images.githubusercontent.com/47611/89354954-044b9e80-d66f-11ea-9f2c-9a879c15df24.png)

**Comment by jhash** [comment]
The way I set this up makes it very difficult to do what you're saying. I either need to rewrite how it's done so it's fixed positioning (which is what I was avoiding so you could still scroll around) or we need a slightly different solution. I tried to just darken the shadow or make the tip bigger but wasn't satisfied with either as a solution
