### ISSUE TITLE
Include a How To and Help section in sidebar that link to different places in zendesk help

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#378]
- change "FAQ" to "Help" in the right sidebar element.
- Add a "How To" that links to this section https://rapidskills.zendesk.com/hc/en-us/sections/360009797231-Work-process-schedules-explained
- Add a Help that links to https://rapidskills.zendesk.com/hc/en-us/sections/360009797231-Work-process-schedules-explained

**Comment by jhash** [comment]
"let’s use info for the How To: https://fontawesome.com/icons/info?style=solid

and the question / circle for help: https://fontawesome.com/icons/question-circle?style=solid
"
