### ISSUE TITLE
A public user can create a clone of the master skills for potential customization

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#38]
The system should be able to clone any OccupationStandard into an `UnregisteredStandard` is how this should work on the back-end. This should copy over:

* work processes
* skills
* title / rapids / onet
* it should set the parent occupation standard as the master that's being cloned

It shouldnt copy over the creator, organization, completed, published, or any files.

**Comment by littleforest** [comment]
@Pcushing since organization does not get copied over, I'm assuming when an occupation_standard is getting cloned, the user has to select a new organization to link it to?

**Comment by littleforest** [comment]
Also, copying over "rapids/onet" just implies that the clone stays linked to the same occupation, right?

**Comment by Pcushing** [comment]
@littleforest yes. Good points. 

They'll have to choose a new organization, and yes, it should be still attached to the same occupation.
