### ISSUE TITLE
Show pencil icon near the thigns you can edit. Make them in edit/non-edit state.

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#381]
They did not know they could type in any of these:

![image](https://user-images.githubusercontent.com/47611/89355675-d36c6900-d670-11ea-86eb-5584c9362cc4.png)

I think we need an editable and un-editable state. If editable, it looks as it with a small save icon in line with the trash can. If not, there's a pencil icon to switch to an editable state

**Comment by jhash** [comment]
I ended up just having a pencil icon that focuses the input to save time

**Comment by Pcushing** [comment]
Great compromise
