### ISSUE TITLE
Thoughts on how to make it more obvious you're in an editable standard now? Shading / header / transition experience?

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#384]
After making a copy of a standard, it wasnt immediately obvious this was theirs to edit. It's a pretty quick transition. Any ideas how to make it more obvious this is yours?

**Comment by jhash** [comment]
I added this little label that says "My Work Schedule"

![Screen Shot 2020-08-07 at 3 53 26 PM](https://user-images.githubusercontent.com/1508098/89683288-46225200-d8c6-11ea-934b-067e4f078594.png)

**Comment by jhash** [comment]
Also, the pencils help
