### ISSUE TITLE
The application can send out emails from a custom domain

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#41]
We'll need to coordinate with their IT staff to get the custom domains set up. 

We should just get the MX records set up at the same time. Let's get an SMTP service set up that'll allow us to play for free for a while. 

I've used most of them. I think I lean towards Mailgun but whatever you want to go with is fine if it avoids payment for a while.

**Comment by littleforest** [comment]
Can get DNS setup instructions after upgrade to the non-free account on Mailgun.

**Comment by littleforest** [comment]
When we get the domain name, then it will give us the DNS instructions.  I can downgrade again if it's going to be awhile.

**Comment by Pcushing** [comment]
the domains is rapidskills.org. I think WIN's IT contractors are just waiting for instructions from us for what to do with it.

**Comment by littleforest** [comment]
**Add DNS records for sending**

Type | Hostname | Enter This Value | Current Value
-- | -- | -- | --
TXT | rapidskills.org | v=spf1 include:mailgun.org ~all | -- 
TXT | krs._domainkey.rapidskills.org | k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHln0bhAqJxBv2sHLY2mFsjeVCoRiNcsVesBLww62yxuDim/feNWyzL3VyEIF1ZcIY8dzgvrTe6uFatYTuhqGejC/pGynSIP3mUgxJQ0qslvmXnYEW7BqZfNdzeWgvLBm8UZIA1VJjKoz2znlS1Kq6LVVdbEXvMtyXZxg6RkJxXQIDAQAB | -- 


Type | Hostname | Priority | Enter This Value | Current Value
-- | -- | -- | -- | --
MX | rapidskills.org | 10 | mxa.mailgun.org | --
MX | rapidskills.org | 10 | mxb.mailgun.org | --

**Add DNS records for tracking**

Type | Hostname | Enter This Value | Current Value
-- | -- | -- | --
CNAME | email.rapidskills.org | mailgun.org  | --


[rapidskills.org-DNS-instructions.pdf](https://github.com/WorkHands/RAPiDSkills/files/3648058/rapidskills.org-DNS-instructions.pdf)

**Comment by Pcushing** [comment]
Can you give me the instructions for them setting up the domains, too? 

So we can (hopefully) get this all done in one shot.

**Comment by littleforest** [comment]
I don't enough permissions on Heroku to set up the domain.  Here is the command if you want to run it:

```
heroku domains:add rapidskills.org -a rapid-skills
```

Then you can look up the target by:
```
heroku domains -a rapid-skills
```

**Comment by littleforest** [comment]
(Or you can give me the "manage permission" on Heroku and I can set it up)

**Comment by littleforest** [comment]
Domain DNS:

Domain Name     |     DNS Record Type  | DNS Target
-- | -- | --
www.rapidskills.org | CNAME        |    regular-galangal-5jvh0fc9mr7ggiz9osce5ke3.herokudns.com
rapidskills.org    |  ALIAS or ANAME  |  colorful-firefly-p49b8w6qjksm21y5d7qrw1zk.herokudns.com
```
