### ISSUE TITLE
An occupation_standard_skill belongs_to a occupation_standard_work_process rather than a skill belonging to a work_process

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#63]
Per discussion here: https://github.com/WorkHands/RAPiDSkills/pull/61#discussion_r336180889

**Comment by littleforest** [comment]
@Pcushing do we really need the OccupationStandardSkill table at all then? Do we really just want an OccupationStandardWorkProcessSkill table?  So we have `occupation_standard_id, work_process_id, skill_id` all getting linked in that way?

**Comment by Pcushing** [comment]
Hmm... Great point. That sounds a lot easier to manage.

I think the `skill_id` has to be optional but otherwise, I think we can get everything we need out of a single join.
