### ISSUE TITLE
Setup API documentation

### ISSUE THREAD

**Issue by littleforest** [WorkHands/RAPiDSkills#68]

**Comment by littleforest** [comment]
@Pcushing could you set up a new repo in Workhands for the RapidSkills documentation?

**Comment by Pcushing** [comment]
@littleforest here you go: https://github.com/WorkHands/RapidSkillsDocs

**Comment by littleforest** [comment]
@Pcushing let me know if there is a rapidskills or workhands logo I can use for the docs. If not, no biggie.

**Comment by Pcushing** [comment]
@littleforest I think @jessicat99 created one, but can you give a quick screenshot so we can see how it'd be used? Light / dark background for example?

**Comment by littleforest** [comment]
It would just be for this upper left corner for our internal API docs. Not customer facing. I can add something later too, not a particularly high priority.

<img width="947" alt="Screen Shot 2019-11-01 at 3 09 29 PM" src="https://user-images.githubusercontent.com/1938665/68059422-b22db500-fcb9-11e9-8b7b-680595129bd7.png">

**Comment by littleforest** [comment]
@Pcushing can you create a "rapidskills-bot" user that has access to this repo and the docs repo, and then add this public key for it:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDExC94NvywrfRNo1dphElkYddNgqHtz8fWuZujMsIPO4dwWNMdS5tKS8yxx59MTMGD89/3VYRDLNafo/bwiLHDKYvOF3r6rt5wnTNy1deew/f3x941X3Y85HsH3jWkyQDPUAU1EF4fiCELnIvFAm49/rkar0COGsyLeXn1U6QBJZk0dlcMIv3uywlOu7exQvm4QVejNpCQRef9PkDvdFT0Rs4VG8mHR9jUvIWIFQcWUE5c3L2Rr03tZoqQY9mBik4ealOySqymE96M3A7UyZtK3Z2p1lldHbPmMn9CGxcWT2RabigG8ENEPxhW+sdCY04Ko2iFflh4RvE3IhAYia5v Codeship/WorkHands/RAPiDSkills

Then Codeship should be able to read both this and the docs repo.

**Comment by Pcushing** [comment]
@littleforest i ran into this. I'll share the login info for this account with you via lastpass so you can manage this as needed.

![image](https://user-images.githubusercontent.com/47611/68146001-e4265d80-feeb-11e9-9a09-5e7401f6f832.png)
