### ISSUE TITLE
A public user can sign up pre-launch to get on the email list

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#72]
Design here: 

https://www.dropbox.com/s/l88grtpyil3m1eo/rapidskils_beta_lp_1.0-pjc.sketch?dl=0

We need this to be live by the end of the week so we can promote for National Apprenticeship Week next week, starting 11/11. We're doing a little bit of fudging on the design because of jessica's being unavailable, but essentially:

- User lands on the homepage 
- User clicks to get beta access (or puts email in footer)
- User is taken to sign up page (prefilled email if added email in footer) to fill out basic form 
- Message displayed that they're signed up and we'll invite when we're ready

You'll need this endpoint: https://github.com/WorkHands/RAPiDSkills/issues/70. @littleforest , can we make sure that @jhash  can submit name + email + organization_name in this create?

After submitting, the front-end should display a message that they're signed up, and we'll let them know when we're ready to invite them in. For this step, do whatever is easiest to implement. I think we'll get more direction from Jessica when she's available again. I'd assume that only the homepage is definitely going to stick around post-launch so simplicity on the rest is preferred.

**Comment by littleforest** [comment]
@Pcushing is `organization_name` required? And I assume that this should create an organization record, correct? We're not just storing the name on the user model for now until we do something more official later, right?

**Comment by Pcushing** [comment]
@littleforest I just created this https://github.com/WorkHands/RAPiDSkills/issues/73. Bit of an oversight on my part that we didnt have any way to associate a user to an org directly. Does that clarify?

**Comment by littleforest** [comment]
Is it required?

**Comment by Pcushing** [comment]
@littleforest I think we should enforce it on the front-end for this use case but the api shouldnt enforce it as i dont see it as a universal requirement for creating a user.
