### ISSUE TITLE
A user has an employer they belong_to

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#73]
Re: https://github.com/WorkHands/RAPiDSkills/issues/72#issuecomment-549503163

Let's just do this formally. Let's include a `employer_id` so we can attach a user to an organization as part of the create user endpoint https://github.com/WorkHands/RAPiDSkills/issues/70.

We should likely support accepting a name or id.

**Comment by littleforest** [comment]
You prefer the association to be called "Employer" rather than "Organization"?

**Comment by Pcushing** [comment]
Good question. There can be a lot of overlapping memberships to different organizations in apprenticeships. This could get a lot more complicated.  

Would prefer to keep this specific + simple that it's the employer relationship.

**Comment by littleforest** [comment]
But `employer_id` will reference an organization, correct?
