### ISSUE TITLE
An admin can add new master skill details

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#8]
For now, let's assume this means they're doing so via ActiveAdmin. This ticket should be the result of us creating the `OccupationStandard` table and then linking it up to ActiveAdmin.

"Masker skill details" really means an occupation_standard that's a "framework"

It should also include the actual skills / work processes associated with that `OccupationStandard`: https://dbdiagram.io/d/5d7aa7d683427516dc0b9bd6

**Comment by littleforest** [comment]
@Pcushing I can use an enum for the OccupationStandards type, correct?  This isn't also STI, right?

**Comment by littleforest** [comment]
@Pcushing did you also want me to add the Organizations table since it is linked to OccupationStandards, or just wait and do that later?

**Comment by Pcushing** [comment]
> I can use an enum for the OccupationStandards type, correct? This isn't also STI, right?

I'm feeling like we may want to just do this now, rather than come back to do it later. I don't yet know how all of the types might imply differences code-wise.

Here's some suggestions for the type and descriptions for your reference:

* `Framework` - an unregistered list of work processes / skills put out by someone like Urban Institute / WIN. There's no intent to register these. They're put out as a resource.
* `Registered` - a list of work processes / skills that's registered with the DOL or some state agency
* `Guideline` - a list of work processes / skills that's pre-approved by DOL and can then be used typically by member organizations for faster approval (ie, National Wood Flooring Association has their guidelines approved so their member companies can get approved quickly using the same thing, but they're not the owner of the standards)
* `Unregistered` - This would be a working copy of standards that _could_ be registered at some point (ie, someone clones any of the above, it's immediately an `Unregistered` standard owned by that organization)

**Comment by Pcushing** [comment]
@littleforest re: 

> did you also want me to add the Organizations table since it is linked to OccupationStandards, or just wait and do that later?

There's going to be lots of overlapping models as we go through. I think this is up to you. If it helps the whole thing make more sense / fit together from the start, go for it.

**Comment by littleforest** [comment]
> I'm feeling like we may want to just do this now, rather than come back to do it later.

Sorry, wasn't clear what you meant by this.  Do you mean we should set it up as STI?

**Comment by Pcushing** [comment]
Yes - let's set it up as STI. The distinction between how the objects will operate isnt clear yet for all cases, but I suspect down-the-line we'll be glad we did.

**Comment by littleforest** [comment]
@Pcushing which of these associations are optional (if any):

* organization
* occupation
* industry
* creator
* parent_occupation_standard

**Comment by Pcushing** [comment]
Optional:
* parent_occupation_standard - this'll only be set if it's cloned from an existing occupation_standard

May be optional:
* industry - i'm not sure how good the data we're going to get is here so i'd assume optional until we know otherwise

The rest are required.
