### ISSUE TITLE
The api can support pulling occupation standards by the current user that includes ones they've created, ones they've liked, or both

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#94]

**Comment by littleforest** [comment]
@jhash proposing this:

 Current user ID = 1

This endpoint returns all favorited occupation standards for current user ([endpoint already exists](https://www.rapidskills.org/api/v1/docs/#list-favorites))
`http://www.rapidskills.org/api/v1/users/1/favorites`

Proposal: Endpoint to return all favorited occupation standards for current user, filtered by ones created by the current user. (NB: `/users/2/favorites` currently returns 401).
`http://www.rapidskills.org/api/v1/users/1/favorites?filter[user]=1`

Proposal: Endpoint to return all occupation standards, filtered by ones created by the current user.
`http://www.rapidskills.org/api/v1/occupation_standards?filter[user]=1`

Please let me know your thoughts.

**Comment by jhash** [comment]
@littleforest B2 for sure. That is the RESTful option as well

**Comment by littleforest** [comment]
@jhash are you okay with this part as well?

> Proposal A: Endpoint to return all favorited occupation standards for current user, filtered by ones created by the current user.
http://www.rapidskills.org/api/v1/users/1/favorites?filter[user]=1

**Comment by littleforest** [comment]
@jhash here are the docs for the new/updated endpoints:

- [Favorites](https://www.rapidskills.org/api/v1/docs/#favorites-list-favorites). See note about filtering by `creator`.

- [List standards owned by current user](https://www.rapidskills.org/api/v1/docs/#users-list-occupation-standards). 

As discussed on our call last week, if you could set it up so you get a list of all favorites with this call: `GET http://www.rapidskills.org/api/v1/users/:user_id/relationships/favorites`, and then create a dictionary to note favorites when the standards endpoint is called: `GET http://www.rapidskills.org/api/v1/occupation_standards`, that would probably be more efficient than me joining to the favorites table on the server-side.
